include:
  - ./postgres/docker-compose.yml
  - ./qdrant/docker-compose.yml
  - ./minio/docker-compose.yml
  - ./embedding/docker-compose.yml
  - ./llm/docker-compose.yml
  - ./document_parsing_service/docker-compose.yml
  - ./graylog/docker-compose.yml
  - ./api/docker-compose.yaml
  - ./frontend/docker-compose.yml
