FROM golang:1.24-alpine AS builder

ARG GOOSE_VERSION=v3.24.1

RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM alpine:3.21

COPY --from=builder /go/bin/goose /usr/local/bin/goose

ENTRYPOINT ["/usr/local/bin/goose"]
