# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import embedding_service.functions_pb2 as functions__pb2


class EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/embedding.v1.EmbeddingService/GetHealth',
                request_serializer=functions__pb2.HealthRequest.SerializeToString,
                response_deserializer=functions__pb2.HealthResponse.FromString,
                )
        self.ParseDocument = channel.stream_stream(
                '/embedding.v1.EmbeddingService/ParseDocument',
                request_serializer=functions__pb2.UploadChunk.SerializeToString,
                response_deserializer=functions__pb2.ParseResponse.FromString,
                )
        self.CreateChunks = channel.stream_stream(
                '/embedding.v1.EmbeddingService/CreateChunks',
                request_serializer=functions__pb2.CreateChunksRequest.SerializeToString,
                response_deserializer=functions__pb2.ChunkResponse.FromString,
                )
        self.EmbedChunks = channel.stream_stream(
                '/embedding.v1.EmbeddingService/EmbedChunks',
                request_serializer=functions__pb2.EmbedChunksRequest.SerializeToString,
                response_deserializer=functions__pb2.EmbedResponse.FromString,
                )


class EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseDocument(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedChunks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=functions__pb2.HealthRequest.FromString,
                    response_serializer=functions__pb2.HealthResponse.SerializeToString,
            ),
            'ParseDocument': grpc.stream_stream_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=functions__pb2.UploadChunk.FromString,
                    response_serializer=functions__pb2.ParseResponse.SerializeToString,
            ),
            'CreateChunks': grpc.stream_stream_rpc_method_handler(
                    servicer.CreateChunks,
                    request_deserializer=functions__pb2.CreateChunksRequest.FromString,
                    response_serializer=functions__pb2.ChunkResponse.SerializeToString,
            ),
            'EmbedChunks': grpc.stream_stream_rpc_method_handler(
                    servicer.EmbedChunks,
                    request_deserializer=functions__pb2.EmbedChunksRequest.FromString,
                    response_serializer=functions__pb2.EmbedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedding.v1.EmbeddingService/GetHealth',
            functions__pb2.HealthRequest.SerializeToString,
            functions__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParseDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/embedding.v1.EmbeddingService/ParseDocument',
            functions__pb2.UploadChunk.SerializeToString,
            functions__pb2.ParseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/embedding.v1.EmbeddingService/CreateChunks',
            functions__pb2.CreateChunksRequest.SerializeToString,
            functions__pb2.ChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmbedChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/embedding.v1.EmbeddingService/EmbedChunks',
            functions__pb2.EmbedChunksRequest.SerializeToString,
            functions__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
